server:
  port: 8761
eureka:
  instance:
    hostname: eureka-server  # eureka实例的主机名
  client:
    register-with-eureka: false #不把自己注册到eureka上，此值默认是 true
    fetch-registry: false #不从eureka上来获取服务的注册信息，因为自己本身就是注册中心，此值默认是 true
    service-url:
      defaultZone: http://localhost:8761/eureka/





